### ISSUE TITLE
Flasche Werte für 23.06

### ISSUE THREAD

**Issue by Tho-Mat** [micb25/dka#10]
Die am 23.06 veröffentlichten Daten enthalten Schlüssel, die via App in der Zeit vom 16.06 bis 23.06 gemeldet wurden.
Deshalb muss man für die % Zahl auch die Summe der vom RKI gemeldeten Infektionen in Relation setzen (4023).
RKI: 345+580+770+601+687+537+503 statt 503
Nach meinen Berechnungen ergeben sich aber auch 44 Personen.
Hier meine Tabelle 
https://github.com/Tho-Mat/corona-stuff/blob/master/%C3%BCberblick.xlsx

User:
```
16-23.06 44      <<< im Laufe des 23.06 wurde der Faktor von 1 auf 10 geändert.
   24.06 11 (incl. 2 Meldungen vom 23.06)
   25.06 19
   26.06 20
   27.06 15 (incl. 1 Meldung vom 26.06)
   28.06 8
   29.06 15 (incl. 1 Meldung vom 28.06)
   30.06 26 (incl. 1 Meldung vom 29.06)
   01.07 18 (incl. 1 Meldung vom 30.06)
   02.07 33 (incl. 1 Meldung vom 01.07)  oder 38 incl. 2 Meldungen vom 01.07 <<< hier wurde der Faktor von 10 auf 5 geändert
   03.07 16
   04.07 11
   05.07 3
   06.07 10
```
Da nicht immer 140 Schlüssel für die "hour" Dateien zusammenkommen werden 1 bis 2 Meldungen manchmal erst am nächsten Tag veröffentlicht.

**Comment by micb25** [comment]
Vielen Dank für den Hinweis. Das Verhältnis mag für diesen Tag zwar weniger genau sein (ich vermeide "falsch", weil wir die "richtigen" Werte nicht kennen), aber es handelt sich nun einmal um Schätzungen. Allerdings sehe ich nicht, dass sich der (manuelle) Aufwand lohnt, diese täglichen Pakete noch genauer zu analysieren und die Tageszahlen zu korrigieren. 

Das wesentlich größere Problem, was noch größere Ungenauigkeiten verursacht, sehe ich aber bei dem Meldeverzug in den RKI-Daten. Das RKI selber kennt die Problematik mit dem Meldeverzug und betreibt aus diesem Grund das [Nowcasting](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile), leider gibt es aber hier keine tagesaktuellen Zahlen, die man verwenden könnte. Um die ganze Problematik etwas aussagekräftiger zu machen, habe ich vor wenigen Tagen die 7-Tages-Durchschnittskurven für das Verhältnis als auch die Korrelation mit den JHU-Daten hinzugefügt.

**Comment by Tho-Mat** [comment]
Des weiteren glaube ich, dass es noch einen Time Shift gibt.
Das RKI meldet z.B. am 7.07. um 8:20
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html
390 Neuinfektionen aber mit stand 7.07 00:00
Das sind also die für den 6.7 neu gemeldeten Infektionen.
Entsprechend 
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-07-06-de.pdf?__blob=publicationFile
219 Neuinfektionen gemeldet am 6.7 für den 5.7. u.s.w.
Die 219 hast du aber für den 6.7 eingetragen.
Es müssen also, glaube ich, alle RKI werte um 1 Tag verschoben werden. Oder habe ich mich vertan.

Das würde aber bedeuten auch der Wert, den ich ober für RKI angegeben habe ist falsch: sollte 4265 sein.
So dass ich in der Summe auf 2,6% komme.
