### ISSUE TITLE
Week numbers seem to be behind by one

### ISSUE THREAD

**Issue by daimpi** [micb25/dka#12]
We're currently (05.08.) in Week 32, but last bars in the weekly diagrams - which seem to depict aggregate data for the current week - are denoted with "KW 31", shouldn't this be "KW 32" ?

Additionally: I'd actually suggest only displaying weekly bar diagrams for weeks which have concluded. Imho this makes the endpoints in those weekly graphs less confusing in general.

**Comment by micb25** [comment]
Thanks for your comments. Since I'd like to see the sums of the current week, I decided to visually change the bar of the current week and I also added a label for the current week. I think that this should fix this issue. :-)

**Comment by daimpi** [comment]
That's a really clever solution. I love it 😊.
