### ISSUE TITLE
Add graph for keys per user

### ISSUE THREAD

**Issue by daimpi** [micb25/dka#14]
Each user can at max upload 13 keys. It seems that recently there has been a strong divergence in the number of users uploading keys vs. actual number keys uploaded:
22.08: 86 people vs 639 keys: 7.4 keys/person
20.08: 91 people vs 948 keys: 10.4 keys/person

My guess would be that maybe some ppl who got tested and wanted to receive their result via app only installed it once they got tested and therefore only very few keys will be submitted.

This information might also be interesting in context of the discussion on how to improve CWA efficiency/uptake in the wishlist repo: https://github.com/corona-warn-app/cwa-wishlist/issues/150.  

That's why I thought it would be nice to have a graph visualizing the keys/person development 🙂.

**Comment by ndegendogo** [comment]
As far as I understand, a positive-tested person uploads her (up to 14) keys in two batches:
first batch is up to 13 keys, for the last 13 days (as far as keys are available), but excluding today's key. And then, on the next day, the remaining key.

Maybe this asymmetric split explains the observed divergence in ratio.

**Comment by daimpi** [comment]
Afaik the German CWA (in contrast to the Swiss app) currently [doesn't have](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-677645128) "last day uploads" integrated: and therefore is actually limited to a maximum of 13 keys/person.

**Comment by ndegendogo** [comment]
Wow - I was not aware that this is not implemented. What a pity. In my understanding the last day would be much more interesting than the old key from 14 days ago.

**Comment by daimpi** [comment]
I think the devs have it on their todo list: https://github.com/corona-warn-app/cwa-app-android/issues/678#issuecomment-650760871 🙂 

But if you go to get a test and self-isolate while waiting for the results, you shouldn't have much contact on the upload day anyway I guess…

**Comment by ndegendogo** [comment]
Well - I am thinking of all the travellors returning home from their holidays. They get a test at the border. They ride home, maybe using public transport. And then their fridge is empty, so they do some shopping. And they start quarantaine after they get their result, not before.
Exactly these contacts will not show up in manual contact tracing. Here the app could be a big benefit.

**Comment by daimpi** [comment]
Hmm… I think the rules are actually that you have to quarantine (at least if come from a high-risk area) until you get the result. But yes, some ppl will not adhere to this. But even if they come back on day 1, get tested and then go shopping, if they get their results the next day, everyone they met on day one will get a warning.

But in principle I agree that it would be better if also the encounters on the upload day would receive a warning.

**Comment by daimpi** [comment]
I just realized that https://ctt.pfstr.de/ is already showing "keys per user".

Given this new info, I don't think this function needs to be duplicated here, so unless you really want to implement such graphs feel free to close this issue @micb25 🙂.

**Comment by daimpi** [comment]
In the meantime I found out that the numbers here
> 22.08: 86 people vs 639 keys: 7.4 keys/person

seem to be distorted by some kind of problem with the packages on this day. I reported this issue in over at @janpf's repo: https://github.com/janpf/ctt/issues/4 🙂.

**Comment by micb25** [comment]
> Given this new info, I don't think this function needs to be duplicated here, so unless you really want to implement such graphs feel free to close this issue @micb25 slightly_smiling_face.

I like the way how @janpf solved it with an interactive plot. Since I'm using non-interactive gnuplot graphs, I might add an "average key length per day" graph in the future. But you're right, this is not really necessary.

> seem to be distorted by some kind of problem with the packages on this day. I reported this issue in over at @janpf's repo: [janpf/ctt#4](https://github.com/janpf/ctt/issues/4) slightly_smiling_face.

Does the difference originate from the different way of analyzing the CWA packages (in @janpf's repo: daily packages; in mine: hourly packages)?

**Comment by daimpi** [comment]
> Does the difference originate from the different way of analyzing the CWA packages (in @janpf's repo: daily packages; in mine: hourly packages)?

Nope, he's actually also [using](https://github.com/janpf/ctt/issues/4#issuecomment-680161642) hourly data for the graphs. There seems to be an issue with the hour 17 package that day (it seems to be missing TRL 6 keys): https://github.com/corona-warn-app/cwa-server/issues/723
