### ISSUE TITLE
Weekly number of uploading users without teleTAN

### ISSUE THREAD

**Issue by cfritzsche** [micb25/dka#16]
Once a week, Telekom releases the total number of requested teleTANs. In the same weekly cadence, we could calculate:
Estimated number of uploading users without teleTAN = people uploading that week - issued teleTANs

Of course not every teleTAN must be used for upload so the actual number of people uploading without teleTAN can be higher.

With this weekly statistic we could better follow the usage of the QR code test retrieval process within CWA.

**Comment by micb25** [comment]
Thanks for your suggestion. This is definitely on my to-do list. Currently, I am planning to convert all the graphs to a more interactive JS-based system, e.g. ApexCharts.js, since some of them become difficult to read.

**Comment by micb25** [comment]
Unfortunately, no statistics regarding the teleTANs have been published by the RKI for over a month now. In their latest [report](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_14102020.pdf?__blob=publicationFile), no data on the number of issued teleTANs were given and I suspect that we won't get any updates on the teleTANs in the future. Thus, I think we can sadly close this issue.

**Comment by cfritzsche** [comment]
Sadly, I agree
