### ISSUE TITLE
Update x-axis of Downloads graph daily

### ISSUE THREAD

**Issue by PalminX** [micb25/dka#18]
Currently, the x-axis of the "Summe ausgegebener TeleTANs" graph is updated daily, even if there is no new data for a day. This makes it easy to see how recent the latest data point is.

The same should be done for the Downloads graph, i.e. expand the x-axis daily, even though new data points might only be entered once a week.

**Comment by micb25** [comment]
It's fixed. Unfortunately, the RKI didn't publish any new numbers since one and a half week.
