### ISSUE TITLE
Plots for CWA downloads differ between master and github.io

### ISSUE THREAD

**Issue by daimpi** [micb25/dka#2]
It seems the plots for the number of CWA downloads is updated on master, but not on the github.io page.
On master the `plot_cwa_downloads.png` contains the data for today (29.06.20) but it is missing from the io page.

**Comment by micb25** [comment]
This seems to be an issue with GitHub itself. I've already recognized that by uploading another commit not related to this specific file it seems to trigger an update of the github.io page.

**Comment by daimpi** [comment]
I see.
Thanks for the the fast response and update :)
And thank you very much for making this page in the first place! It's really amazing to have all this CWA related information collected in one place and made easily digestible with nice visualizations 😊.

**Comment by micb25** [comment]
The missing timezone in [_config.yml](https://github.com/micb25/dka/blob/master/_config.yml) didn't trigger the update of the website.
