### ISSUE TITLE
Auswertungsgrafiken Stand 30.12.2020

### ISSUE THREAD

**Issue by gusowski1** [micb25/dka#22]
Die Graphen auf https://micb25.github.io/dka/ werden seit dem 30.12.2020 nicht mehr upgedated.

**Comment by micb25** [comment]
Aufgrund des Jahreswechsels musste ich erst einmal etwas Zeit finden, um ein paar kleinere Anpassungen vorzunehmen (Hauptgrund: die korrekte Zählweise der Wochennummern in den Wochenstatistiken). Die Daten habe ich in der Zwischenzeit selbstverständlich weiter gesammelt. Es sollte jetzt alles wieder funktionieren und regelmäßige Updates können wieder erfolgen. :)
