### ISSUE TITLE
orthographic mistake

### ISSUE THREAD

**Issue by geos-github** [micb25/dka#8]
There's a comma missing in one of the graphs' titles. It should spell "Verhältnis zwischen positiv getesteten Personen, die Diagnoseschlüssel teilen, und den gemeldeten Neuinfektionen".

**Comment by geos-github** [comment]
Oh, and once you are there, "mitteilen" would be a much more appropriate verb in German, or maybe "veröffentlichen", "publizieren", or if you want to be more technical "hochladen", would be a better wording.

**Comment by micb25** [comment]
Thank you for spotting the mistake!
