### ISSUE TITLE
Redundant graphs in "Verteilung Transmission Risk Level (TRL) in Diagnoseschlüsseln"

### ISSUE THREAD

**Issue by PalminX** [micb25/dka#9]
I think the two graphs in "Verteilung Transmission Risk Level (TRL) in Diagnoseschlüsseln" are redundant, since they are only scaled with respect to each other.

Wouldn't it be simpler to just include the relative ratios next to the absolute numbers in the first graph (i.e. "4649 (30.2 %)" instead of just "4649"?

**Comment by micb25** [comment]
Thanks for the hint. I have merged both data into one graph.
